baseURL = "http://localhost:1313/QUESTDB_website/"
#baseURL = "https://lcpq.github.io/QUESTDB_website/"
canonifyurls  = true

languageCode = "en-us"
metaDataFormat = "yaml"
DateForm = "12-30-2006"
 title = "QUEST: a database of highly-accurate excitation energies"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Params]
  hometitle = "QUESTDB"
  logo="img/TOC_JPCL.png"
  subtitle = "QUantum Excited STate DataBase"
[[Params.bigimg]]
  src = "img/QUEST-home.png"
  desc = "A mountaineering strategy to excited states"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[Author]
  name = "M. Véril"
  email = "mveril@irsamc.ups-tlse.fr"
  github = "LCPQ/QUESTDB_website"
  twitter = "LCPQ_UMR5626"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Dataset"
    url = "dataset"
    weight = 2

[[menu.main]]
    name = "Subsets"
    url = "subsets"
    weight = 3

[[menu.main]]
    name = "References"
    url = "references"
    weight = 4

